# h2 Database
spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/testDB
    username: sa
    password:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
    hibernate:
      ddl-auto: create

# logging
logging:
#  file:
#    path: /Users/hong/Logs/kotlin-spring
#    max-size: 500MB
#    max-history: 10
  level:
    root: info
    com:
      ho:
        gamble: debug
