INSERT INTO TBL_MEMBER (MEMBER_NAME, MEMBER_NICK_NAME, MEMBER_LOGIN_ID, MEMBER_PASSWORD, MEMBER_ZIPCODE, MEMBER_ADDRESS1, MEMBER_ADDRESS2, CREATED_BY, UPDATED_BY)
VALUES ('김준호', '쭌홍', 'ho980719', '1234', '', '서울특별시 동작구 사당로2길 48', '801호', '관리자', '관리자');
